// sectorsData.js
import {
  Trees,
  UtensilsCrossed,
  House,
  Users,
  GraduationCap,
  Tractor,
  Fish,
  Landmark,
  HeartPulse,
  Scale,
  Dna,
  Baby,
  Building2,
  HandHeart,
  Accessibility,
  ShieldAlert,
  Droplets,
  BookOpen,
  Home,
  Ribbon,
  Globe,
  Wifi,
  Briefcase,
  MapPinned,
  Gavel,
  Coins,
  Factory,
  UsersRound,
  Sun,
  Apple,
  Vote,
  Lock,
  Wheat,
  FlaskConical,
  Microscope,
  Medal,
  Plane,
  Mountain,
  Building,
  Wrench,
  Waves,
  Megaphone,
  PawPrint,
  Church,
  Banknote,
  Car,
  Lightbulb,
} from "lucide-react";

export const primarySectors = [
  {
    id: 1,
    icon: Trees,
    title: "Environment & Forests",
    description: "Promoting environmental conservation and sustainable ecosystems.",
  },
  {
    id: 2,
    icon: UtensilsCrossed,
    title: "Food Processing",
    description: "Supporting food production, value addition and nutrition initiatives.",
  },
  {
    id: 3,
    icon: House,
    title: "Housing",
    description: "Improving access to safe and sustainable housing for communities.",
  },
  {
    id: 4,
    icon: Users,
    title: "Women's Development",
    description: "Empowering women through education, welfare and opportunities.",
  },
  {
    id: 5,
    icon: GraduationCap,
    title: "Skill Development",
    description: "Building employable skills through training and education.",
  },
];

export const secondarySectors = [
  {
    id: 6,
    icon: Tractor,
    title: "Agriculture",
    description: "Supporting sustainable agricultural development and farmer welfare.",
  },
  {
    id: 7,
    icon: PawPrint,
    title: "Animal Husbandry",
    description: "Promoting livestock management and veterinary care.",
  },
  {
    id: 8,
    icon: Fish,
    title: "Dairying & Fisheries",
    description: "Strengthening dairy production and fisheries for rural livelihoods.",
  },
  {
    id: 9,
    icon: Landmark,
    title: "Art & Culture",
    description: "Preserving heritage, promoting cultural diversity and artistic traditions.",
  },
  {
    id: 10,
    icon: Dna,
    title: "Biotechnology",
    description: "Advancing bio-science research for health, agriculture and environment.",
  },
  {
    id: 11,
    icon: Baby,
    title: "Children",
    description: "Protecting child rights, welfare, education and development.",
  },
  {
    id: 12,
    icon: Building2,
    title: "Civic Issues",
    description: "Addressing urban governance, public infrastructure and citizen services.",
  },
  {
    id: 13,
    icon: HandHeart,
    title: "Dalit Upliftment",
    description: "Empowering marginalized communities through rights and social justice.",
  },
  {
    id: 14,
    icon: Accessibility,
    title: "Differently Abled",
    description: "Ensuring inclusion, accessibility and equal opportunity for all abilities.",
  },
  {
    id: 15,
    icon: ShieldAlert,
    title: "Disaster Management",
    description: "Building resilience through disaster preparedness and relief operations.",
  },
  {
    id: 16,
    icon: Droplets,
    title: "Drinking Water",
    description: "Ensuring clean and safe drinking water access for all communities.",
  },
  {
    id: 17,
    icon: BookOpen,
    title: "Education & Literacy",
    description: "Promoting universal education, literacy and academic development.",
  },
  {
    id: 18,
    icon: Home,
    title: "Aged/Elderly",
    description: "Supporting elderly welfare through old age homes and care programs.",
  },
  {
    id: 19,
    icon: HeartPulse,
    title: "Health & Family Welfare",
    description: "Improving public healthcare, family welfare and medical accessibility.",
  },
  {
    id: 20,
    icon: Ribbon,
    title: "HIV/AIDS",
    description: "Fighting HIV/AIDS through awareness, prevention and support programs.",
  },
  {
    id: 21,
    icon: Scale,
    title: "Human Rights",
    description: "Protecting fundamental rights, dignity, justice and equality for all.",
  },
  {
    id: 22,
    icon: Wifi,
    title: "Information & Communication Technology",
    description: "Bridging the digital divide through technology access and education.",
  },
  {
    id: 23,
    icon: Briefcase,
    title: "Labour & Employment",
    description: "Advocating for workers' rights, fair wages and employment opportunities.",
  },
  {
    id: 24,
    icon: MapPinned,
    title: "Land Resources",
    description: "Managing land use, rights and sustainable resource development.",
  },
  {
    id: 25,
    icon: Gavel,
    title: "Legal Awareness & Aid",
    description: "Providing legal literacy, free aid and access to justice for all.",
  },
  {
    id: 26,
    icon: Coins,
    title: "Micro Finance (SHGs)",
    description: "Empowering communities through self-help groups and micro-lending.",
  },
  {
    id: 27,
    icon: Factory,
    title: "Micro Small & Medium Enterprises",
    description: "Supporting MSMEs for economic growth and local entrepreneurship.",
  },
  {
    id: 28,
    icon: UsersRound,
    title: "Minority Upliftment",
    description: "Promoting inclusion, welfare and development of minority communities.",
  },
  {
    id: 29,
    icon: Sun,
    title: "New & Renewable Energy",
    description: "Advancing clean energy solutions for sustainable development.",
  },
  {
    id: 30,
    icon: Apple,
    title: "Nutrition",
    description: "Combating malnutrition through food security and nutrition programs.",
  },
  {
    id: 31,
    icon: Vote,
    title: "Panchayati Raj",
    description: "Strengthening grassroots democracy and local self-governance.",
  },
  {
    id: 32,
    icon: Lock,
    title: "Prisoner's Issues",
    description: "Advocating for prisoner rights, rehabilitation and reform.",
  },
  {
    id: 33,
    icon: Megaphone,
    title: "Right to Information & Advocacy",
    description: "Promoting transparency, accountability and citizen participation.",
  },
  {
    id: 34,
    icon: Wheat,
    title: "Rural Development & Poverty Alleviation",
    description: "Driving rural growth through development programs and poverty reduction.",
  },
  {
    id: 35,
    icon: FlaskConical,
    title: "Science & Technology",
    description: "Harnessing science and technology for societal advancement.",
  },
  {
    id: 36,
    icon: Microscope,
    title: "Scientific & Industrial Research",
    description: "Promoting research innovation for industrial and scientific progress.",
  },
  {
    id: 37,
    icon: Medal,
    title: "Sports",
    description: "Encouraging sports participation, fitness and youth development.",
  },
  {
    id: 38,
    icon: Plane,
    title: "Tourism",
    description: "Promoting sustainable tourism for economic and cultural growth.",
  },
  {
    id: 39,
    icon: Mountain,
    title: "Tribal Affairs",
    description: "Protecting tribal rights, culture and sustainable development.",
  },
  {
    id: 40,
    icon: Building,
    title: "Urban Development & Poverty Alleviation",
    description: "Improving urban living standards and reducing city poverty.",
  },
  {
    id: 41,
    icon: Wrench,
    title: "Vocational Training",
    description: "Providing skill-based training for employment and self-reliance.",
  },
  {
    id: 42,
    icon: Waves,
    title: "Water Resources",
    description: "Managing water conservation, irrigation and resource sustainability.",
  },
  {
    id: 43,
    icon: Globe,
    title: "Youth Affairs",
    description: "Empowering youth through leadership, education and opportunities.",
  },
  {
    id: 44,
    icon: PawPrint,
    title: "Animal Welfare",
    description: "Protecting animal rights and promoting humane treatment.",
  },
  {
    id: 45,
    icon: Church,
    title: "Religious",
    description: "Promoting interfaith harmony and religious freedom.",
  },
  {
    id: 46,
    icon: Banknote,
    title: "Electoral Funding & Donation",
    description: "Ensuring transparency and accountability in electoral financing.",
  },
  {
    id: 47,
    icon: Car,
    title: "Road Safety",
    description: "Advocating for traffic safety, awareness and accident prevention.",
  },
  {
    id: 48,
    icon: Lightbulb,
    title: "Think Tank",
    description: "Driving policy research, innovation and strategic thought leadership.",
  },
];